import { Stack, router } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { bridgeConcepts, compareConcepts, discoverPath } from "@/lib/graph-paths";
import { useRelationshipStore } from "@/lib/relationship-store";

export default function GraphToolsScreen() {
  const { concepts, connections } = useRelationshipStore();
  const [startId, setStartId] = useState(concepts[0]?.id ?? "");
  const [endId, setEndId] = useState(concepts[1]?.id ?? concepts[0]?.id ?? "");
  const path = useMemo(() => discoverPath(concepts, connections, startId, endId), [concepts, connections, startId, endId]);
  const left = concepts.find((concept) => concept.id === startId); const right = concepts.find((concept) => concept.id === endId);
  const comparison = left && right ? compareConcepts(left, right, connections) : null;
  const bridges = useMemo(() => bridgeConcepts(concepts, connections), [concepts, connections]);
  return <ScreenContainer containerClassName="bg-background"><Stack.Screen options={{ headerShown: false }} /><FlatList data={[]} renderItem={null} contentContainerStyle={styles.content} ListHeaderComponent={<View><View style={styles.nav}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.backButton, pressed && styles.pressed]}><Text style={styles.backText}>‹</Text></Pressable><View><Text style={styles.eyebrow}>GRAPH REASONING</Text><Text style={styles.title}>Paths and comparison</Text></View></View><Text style={styles.description}>Trace how two ideas connect, compare their context, and identify the concepts that bridge your graph.</Text><Selector label="START CONCEPT" concepts={concepts} selected={startId} onSelect={setStartId} tint="#8D82FF" /><Selector label="END CONCEPT" concepts={concepts} selected={endId} onSelect={setEndId} tint="#48D6E8" />{left && right ? <View style={styles.pathCard}><Text style={styles.cardEyebrow}>SHORTEST LOCAL PATH</Text>{path ? <><View style={styles.pathRow}>{path.conceptIds.map((id, index) => { const concept = concepts.find((entry) => entry.id === id); return <View key={`${id}-${index}`} style={styles.pathPart}><Pressable onPress={() => router.push(`/concept/${id}`)} style={({ pressed }) => [styles.pathNode, pressed && styles.pressed]}><Text style={styles.pathNodeText}>{concept?.title}</Text></Pressable>{index < path.connections.length ? <Text style={styles.pathVerb}>{path.connections[index].relationship}</Text> : null}</View>; })}</View><Text style={styles.pathDetail}>{path.connections.length} relationship{path.connections.length === 1 ? "" : "s"} connect these two ideas.</Text></> : <Text style={styles.pathEmpty}>These concepts are not yet connected by a local graph path.</Text>}</View> : null}{comparison ? <View style={styles.compareCard}><Text style={styles.cardEyebrow}>COMPARISON</Text><Text style={styles.compareTitle}>{left?.title} and {right?.title}</Text><View style={styles.compareRow}><Compare label="Shared tags" value={comparison.sharedTags.length ? comparison.sharedTags.map((tag) => `#${tag}`).join(" ") : "None yet"} /><Compare label="Direct link" value={comparison.directConnection ? comparison.directConnection.relationship : "No direct link"} /><Compare label="Combined links" value={`${comparison.combinedLinks}`} /></View></View> : null}<Text style={styles.sectionLabel}>BRIDGE CONCEPTS</Text><View style={styles.bridgeList}>{bridges.map((concept) => <Pressable key={concept.id} onPress={() => router.push(`/concept/${concept.id}`)} style={({ pressed }) => [styles.bridge, pressed && styles.pressed]}><View style={[styles.bridgeDot, { backgroundColor: concept.color }]} /><View style={styles.bridgeCopy}><Text style={styles.bridgeTitle}>{concept.title}</Text><Text style={styles.bridgeDetail}>{concept.kind} · connects multiple local paths</Text></View><Text style={styles.arrow}>›</Text></Pressable>)}</View></View>} /></ScreenContainer>;
}

function Selector({ label, concepts, selected, onSelect, tint }: { label: string; concepts: ReturnType<typeof useRelationshipStore>["concepts"]; selected: string; onSelect: (id: string) => void; tint: string }) { return <View style={styles.selector}><Text style={styles.selectorLabel}>{label}</Text><View style={styles.selectorRow}>{concepts.map((concept) => <Pressable key={concept.id} onPress={() => onSelect(concept.id)} style={({ pressed }) => [styles.choice, selected === concept.id && { borderColor: tint, backgroundColor: "#252A50" }, pressed && styles.pressed]}><Text style={[styles.choiceText, selected === concept.id && { color: "#F3F6FC" }]}>{concept.title}</Text></Pressable>)}</View></View>; }
function Compare({ label, value }: { label: string; value: string }) { return <View style={styles.compare}><Text style={styles.compareLabel}>{label.toUpperCase()}</Text><Text style={styles.compareValue}>{value}</Text></View>; }
const styles = StyleSheet.create({
  content: { width: "100%", maxWidth: 480, alignSelf: "center", paddingHorizontal: 20, paddingTop: 10, paddingBottom: 50 }, nav: { flexDirection: "row", gap: 12, alignItems: "center", marginBottom: 14 }, backButton: { width: 42, height: 42, borderRadius: 21, justifyContent: "center", alignItems: "center", backgroundColor: "#151C2E" }, backText: { color: "#F3F6FC", fontSize: 33, lineHeight: 35, marginTop: -3 }, eyebrow: { color: "#BDB5FF", fontSize: 9, letterSpacing: 1.1, fontWeight: "900" }, title: { color: "#F3F6FC", fontSize: 22, fontWeight: "800", marginTop: 3 }, description: { color: "#A8B7CF", fontSize: 13, lineHeight: 20, marginBottom: 16 }, selector: { marginTop: 13 }, selectorLabel: { color: "#8190AA", fontSize: 9, letterSpacing: 1, fontWeight: "900", marginBottom: 7 }, selectorRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 }, choice: { minHeight: 33, paddingHorizontal: 10, borderRadius: 10, justifyContent: "center", backgroundColor: "#1A263E", borderWidth: 1, borderColor: "#33445F" }, choiceText: { color: "#AAB8CC", fontSize: 10, fontWeight: "800" }, pathCard: { borderRadius: 20, padding: 15, marginTop: 20, backgroundColor: "#171C39", borderWidth: 1, borderColor: "#645CBF" }, cardEyebrow: { color: "#9D94FF", fontSize: 9, letterSpacing: 1, fontWeight: "900" }, pathRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, alignItems: "center", marginTop: 11 }, pathPart: { flexDirection: "row", gap: 6, alignItems: "center" }, pathNode: { borderRadius: 9, backgroundColor: "#2A3161", paddingHorizontal: 9, paddingVertical: 7 }, pathNodeText: { color: "#F0EFFF", fontSize: 11, fontWeight: "900" }, pathVerb: { color: "#B9B4FF", fontSize: 9, fontWeight: "800", maxWidth: 70 }, pathDetail: { color: "#A8B2D2", fontSize: 11, lineHeight: 17, marginTop: 10 }, pathEmpty: { color: "#FFBF99", fontSize: 12, lineHeight: 18, marginTop: 9 }, compareCard: { borderRadius: 20, padding: 15, marginTop: 12, backgroundColor: "#102533", borderWidth: 1, borderColor: "#336275" }, compareTitle: { color: "#E6F6F8", fontSize: 15, fontWeight: "900", marginTop: 5 }, compareRow: { flexDirection: "row", gap: 7, marginTop: 12 }, compare: { flex: 1 }, compareLabel: { color: "#74AEBC", fontSize: 8, letterSpacing: 0.8, fontWeight: "900" }, compareValue: { color: "#D8EBF0", fontSize: 11, lineHeight: 16, marginTop: 4, fontWeight: "700" }, sectionLabel: { color: "#8190AA", fontSize: 9, letterSpacing: 1, fontWeight: "900", marginTop: 20, marginBottom: 8 }, bridgeList: { gap: 7 }, bridge: { minHeight: 57, borderRadius: 14, backgroundColor: "#151C2E", borderWidth: 1, borderColor: "#2E3D5A", paddingHorizontal: 12, flexDirection: "row", alignItems: "center" }, bridgeDot: { width: 10, height: 10, borderRadius: 5, marginRight: 10 }, bridgeCopy: { flex: 1 }, bridgeTitle: { color: "#E7EDF8", fontSize: 12, fontWeight: "900" }, bridgeDetail: { color: "#8E9DB5", fontSize: 10, marginTop: 3 }, arrow: { color: "#BEB8FF", fontSize: 23 }, pressed: { opacity: 0.7, transform: [{ scale: 0.98 }] },
});
