import AsyncStorage from "@react-native-async-storage/async-storage";
import { Stack, router } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { evidenceReviewSummary } from "@/lib/evidence-review";
import { maintenanceCues } from "@/lib/maintenance-review";
import { useRelationshipStore } from "@/lib/relationship-store";

const REVIEW_KEY = "offline-knowledge-graph.weekly-review.v1";
export default function WeeklyReviewScreen() {
  const { concepts, connections } = useRelationshipStore();
  const [lastReviewed, setLastReviewed] = useState<number | null>(null);
  useEffect(() => { AsyncStorage.getItem(REVIEW_KEY).then((value) => { const parsed = Number(value); if (Number.isFinite(parsed) && parsed > 0) setLastReviewed(parsed); }).catch(() => undefined); }, []);
  const cues = useMemo(() => maintenanceCues(concepts, connections), [concepts, connections]);
  const evidence = useMemo(() => evidenceReviewSummary(concepts, connections), [concepts, connections]);
  const completeReview = () => { const now = Date.now(); setLastReviewed(now); void AsyncStorage.setItem(REVIEW_KEY, String(now)); };
  return <ScreenContainer containerClassName="bg-background"><Stack.Screen options={{ headerShown: false }} /><FlatList data={cues} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View><View style={styles.nav}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.backButton, pressed && styles.pressed]}><Text style={styles.backText}>‹</Text></Pressable><View><Text style={styles.eyebrow}>LOCAL MAINTENANCE</Text><Text style={styles.title}>Weekly review</Text></View></View><Text style={styles.description}>Use a short, private review cycle to keep your graph connected, supported, and ready for the next piece of research.</Text><View style={styles.statusCard}><Text style={styles.statusEyebrow}>REVIEW STATUS</Text><Text style={styles.statusTitle}>{lastReviewed ? `Completed ${new Date(lastReviewed).toLocaleDateString()}` : "Ready for your first review"}</Text><Text style={styles.statusText}>{lastReviewed ? "Your last review was saved on this device. New changes can be reviewed whenever you return." : "Work through the cues below, then mark this review complete."}</Text><Pressable onPress={completeReview} style={({ pressed }) => [styles.completeButton, pressed && styles.pressed]}><Text style={styles.completeText}>Mark review complete</Text><Text style={styles.completeIcon}>✓</Text></Pressable></View><View style={styles.statsRow}><Metric value={`${concepts.length}`} label="Active ideas" /><Metric value={`${connections.length}`} label="Active links" /><Metric value={`${evidence.attention}`} label="Evidence cues" /></View><Text style={styles.sectionLabel}>RECOMMENDED ACTIONS</Text></View>} renderItem={({ item }) => <View style={[styles.cue, item.tone === "attention" && styles.cueAttention, item.tone === "research" && styles.cueResearch]}><View style={styles.cueCopy}><Text style={styles.cueTitle}>{item.title}</Text><Text style={styles.cueDetail}>{item.detail}</Text></View><Pressable onPress={() => item.id === "weak" || item.id === "uncited" ? router.push("/evidence-review" as never) : item.id === "isolated" ? router.push("/graph-tools" as never) : router.push("/(tabs)/explore" as never)} style={({ pressed }) => [styles.cueAction, pressed && styles.pressed]}><Text style={styles.cueActionText}>{item.id === "healthy" ? "Explore" : "Review"}</Text></Pressable></View>} ListFooterComponent={<View style={styles.footCard}><Text style={styles.footTitle}>A lightweight practice</Text><Text style={styles.footText}>This dashboard creates no account and no background notifications. It simply turns the current local graph into a focused maintenance checklist whenever you open it.</Text></View>} /></ScreenContainer>;
}
function Metric({ value, label }: { value: string; label: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({
  content: { width: "100%", maxWidth: 480, alignSelf: "center", paddingHorizontal: 20, paddingTop: 10, paddingBottom: 50 }, nav: { flexDirection: "row", gap: 12, alignItems: "center", marginBottom: 14 }, backButton: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center", backgroundColor: "#151C2E" }, backText: { color: "#F3F6FC", fontSize: 33, lineHeight: 35, marginTop: -3 }, eyebrow: { color: "#FFCE71", fontSize: 9, letterSpacing: 1.1, fontWeight: "900" }, title: { color: "#F3F6FC", fontSize: 22, fontWeight: "800", marginTop: 3 }, description: { color: "#A8B7CF", fontSize: 13, lineHeight: 20, marginBottom: 16 }, statusCard: { borderRadius: 20, padding: 16, backgroundColor: "#2A263B", borderWidth: 1, borderColor: "#695E93" }, statusEyebrow: { color: "#D2C8FF", fontSize: 9, letterSpacing: 1, fontWeight: "900" }, statusTitle: { color: "#F0ECFF", fontSize: 17, fontWeight: "900", marginTop: 5 }, statusText: { color: "#BBB6D5", fontSize: 12, lineHeight: 18, marginTop: 6 }, completeButton: { minHeight: 43, borderRadius: 12, marginTop: 13, paddingHorizontal: 13, backgroundColor: "#8577E9", flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, completeText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" }, completeIcon: { color: "#FFFFFF", fontSize: 17, fontWeight: "900" }, statsRow: { flexDirection: "row", gap: 8, marginTop: 12 }, metric: { flex: 1, minHeight: 58, borderRadius: 14, justifyContent: "center", alignItems: "center", backgroundColor: "#151C2E", borderWidth: 1, borderColor: "#2E3C58" }, metricValue: { color: "#EAF0FA", fontSize: 17, fontWeight: "900" }, metricLabel: { color: "#8493AC", fontSize: 9, fontWeight: "800", marginTop: 3 }, sectionLabel: { color: "#8190AA", fontSize: 9, letterSpacing: 1, fontWeight: "900", marginTop: 20, marginBottom: 9 }, cue: { minHeight: 85, borderRadius: 17, padding: 13, backgroundColor: "#17243B", borderWidth: 1, borderColor: "#355675", marginBottom: 8, flexDirection: "row", alignItems: "center" }, cueAttention: { backgroundColor: "#2B202B", borderColor: "#704256" }, cueResearch: { backgroundColor: "#102A31", borderColor: "#336E73" }, cueCopy: { flex: 1, paddingRight: 8 }, cueTitle: { color: "#E7EFF9", fontSize: 13, fontWeight: "900" }, cueDetail: { color: "#9AABC4", fontSize: 11, lineHeight: 16, marginTop: 4 }, cueAction: { minHeight: 34, borderRadius: 9, paddingHorizontal: 9, justifyContent: "center", backgroundColor: "#273651" }, cueActionText: { color: "#D6D3FF", fontSize: 10, fontWeight: "900" }, footCard: { borderRadius: 17, backgroundColor: "#111A2D", borderWidth: 1, borderColor: "#2D3C58", padding: 14, marginTop: 8 }, footTitle: { color: "#E7EDF8", fontSize: 13, fontWeight: "900" }, footText: { color: "#8798B4", fontSize: 11, lineHeight: 17, marginTop: 5 }, pressed: { opacity: 0.7, transform: [{ scale: 0.98 }] },
});
