import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type PropsWithChildren } from "react";

export type ResearchQuestion = { id: string; title: string; prompt: string; openGap: string; supportingConceptIds: string[]; counterpointConceptIds: string[]; createdAt: number; updatedAt: number };
export type ResearchQuestionInput = Pick<ResearchQuestion, "title" | "prompt" | "openGap">;
const STORAGE_KEY = "offline-knowledge-graph.research-questions.v1";
const cleanIds = (ids: string[]) => [...new Set(ids.filter(Boolean))];
export function createResearchQuestion(input: ResearchQuestionInput, now = Date.now()): ResearchQuestion { const title = input.title.trim().slice(0, 150); return { id: `question-${now.toString(36)}-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "research"}`, title, prompt: input.prompt.trim().slice(0, 2_000), openGap: input.openGap.trim().slice(0, 1_000), supportingConceptIds: [], counterpointConceptIds: [], createdAt: now, updatedAt: now }; }
export function isResearchQuestion(value: unknown): value is ResearchQuestion { if (!value || typeof value !== "object") return false; const item = value as Partial<ResearchQuestion>; return typeof item.id === "string" && typeof item.title === "string" && typeof item.prompt === "string" && typeof item.openGap === "string" && Array.isArray(item.supportingConceptIds) && Array.isArray(item.counterpointConceptIds) && item.supportingConceptIds.every((id) => typeof id === "string") && item.counterpointConceptIds.every((id) => typeof id === "string") && typeof item.createdAt === "number" && typeof item.updatedAt === "number"; }
type ResearchQuestionValue = { questions: ResearchQuestion[]; isReady: boolean; addQuestion: (input: ResearchQuestionInput) => ResearchQuestion; updateQuestion: (id: string, changes: Partial<ResearchQuestionInput>) => void; removeQuestion: (id: string) => void; toggleConceptRole: (questionId: string, conceptId: string, role: "support" | "counterpoint") => void };
const ResearchQuestionContext = createContext<ResearchQuestionValue | null>(null);
export function ResearchQuestionProvider({ children }: PropsWithChildren) { const [questions, setQuestions] = useState<ResearchQuestion[]>([]); const [isReady, setIsReady] = useState(false); useEffect(() => { AsyncStorage.getItem(STORAGE_KEY).then((stored) => { if (!stored) return; try { const parsed: unknown = JSON.parse(stored); if (Array.isArray(parsed)) setQuestions(parsed.filter(isResearchQuestion).sort((a, b) => b.updatedAt - a.updatedAt)); } catch { setQuestions([]); } }).catch(() => undefined).finally(() => setIsReady(true)); }, []); useEffect(() => { if (isReady) void AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(questions)); }, [questions, isReady]); const addQuestion = useCallback((input: ResearchQuestionInput) => { const question = createResearchQuestion(input); setQuestions((current) => [question, ...current]); return question; }, []); const updateQuestion = useCallback((id: string, changes: Partial<ResearchQuestionInput>) => setQuestions((current) => current.map((question) => question.id !== id ? question : { ...question, title: changes.title === undefined ? question.title : changes.title.trim().slice(0, 150), prompt: changes.prompt === undefined ? question.prompt : changes.prompt.trim().slice(0, 2_000), openGap: changes.openGap === undefined ? question.openGap : changes.openGap.trim().slice(0, 1_000), updatedAt: Date.now() })), []); const removeQuestion = useCallback((id: string) => setQuestions((current) => current.filter((question) => question.id !== id)), []); const toggleConceptRole = useCallback((questionId: string, conceptId: string, role: "support" | "counterpoint") => setQuestions((current) => current.map((question) => { if (question.id !== questionId) return question; const support = question.supportingConceptIds; const counterpoint = question.counterpointConceptIds; if (role === "support") return { ...question, supportingConceptIds: support.includes(conceptId) ? support.filter((id) => id !== conceptId) : cleanIds([...support, conceptId]), counterpointConceptIds: counterpoint.filter((id) => id !== conceptId), updatedAt: Date.now() }; return { ...question, supportingConceptIds: support.filter((id) => id !== conceptId), counterpointConceptIds: counterpoint.includes(conceptId) ? counterpoint.filter((id) => id !== conceptId) : cleanIds([...counterpoint, conceptId]), updatedAt: Date.now() }; })), []); const value = useMemo(() => ({ questions, isReady, addQuestion, updateQuestion, removeQuestion, toggleConceptRole }), [questions, isReady, addQuestion, updateQuestion, removeQuestion, toggleConceptRole]); return <ResearchQuestionContext.Provider value={value}>{children}</ResearchQuestionContext.Provider>; }
export function useResearchQuestions() { const context = useContext(ResearchQuestionContext); if (!context) throw new Error("useResearchQuestions must be used within ResearchQuestionProvider"); return context; }
