import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type PropsWithChildren } from "react";

export type SuggestionSignal = "shared-tags" | "shared-neighbors" | "shared-source" | "same-kind";
export type SuggestionOutcome = "accepted" | "dismissed";
export type SuggestionFeedbackReason = "matches-judgment" | "useful-evidence" | "not-relevant" | "insufficient-evidence" | "wrong-relationship";
export const feedbackReasonLabels: Record<SuggestionFeedbackReason, string> = { "matches-judgment": "Matches my judgment", "useful-evidence": "Useful local evidence", "not-relevant": "Not relevant", "insufficient-evidence": "Insufficient evidence", "wrong-relationship": "Wrong relationship" };
export type SuggestionFeedbackEvent = { suggestionId: string; outcome: SuggestionOutcome; signals: SuggestionSignal[]; reason?: SuggestionFeedbackReason; label?: string; createdAt: number };
export type SuggestionFeedback = { events: SuggestionFeedbackEvent[] };
export type FeedbackProfileBundle = { schemaVersion: 1; exportedAt: string; feedback: SuggestionFeedback };
export type FeedbackImportPreview = { incomingEvents: number; newEvents: number; newerReplacements: number; unchanged: number };
export const SUGGESTION_FEEDBACK_KEY = "offline-knowledge-graph.suggestion-feedback.v1";
export const emptySuggestionFeedback = (): SuggestionFeedback => ({ events: [] });
const isSignal = (signal: unknown): signal is SuggestionSignal => signal === "shared-tags" || signal === "shared-neighbors" || signal === "shared-source" || signal === "same-kind";
const isReason = (reason: unknown): reason is SuggestionFeedbackReason => reason === "matches-judgment" || reason === "useful-evidence" || reason === "not-relevant" || reason === "insufficient-evidence" || reason === "wrong-relationship";
export function isSuggestionFeedback(value: unknown): value is SuggestionFeedback { return Boolean(value) && typeof value === "object" && Array.isArray((value as Partial<SuggestionFeedback>).events) && (value as Partial<SuggestionFeedback>).events?.every((event) => event && typeof event.suggestionId === "string" && (event.outcome === "accepted" || event.outcome === "dismissed") && Array.isArray(event.signals) && event.signals.every(isSignal) && (event.reason === undefined || isReason(event.reason)) && (event.label === undefined || typeof event.label === "string") && typeof event.createdAt === "number") === true; }
export function appendSuggestionFeedback(current: SuggestionFeedback, event: Omit<SuggestionFeedbackEvent, "createdAt">, now = Date.now()): SuggestionFeedback { const previous = current.events.filter((entry) => entry.suggestionId !== event.suggestionId); return { events: [{ ...event, signals: [...new Set(event.signals)], createdAt: now }, ...previous].slice(0, 100) }; }
export function updateFeedbackReason(current: SuggestionFeedback, suggestionId: string, reason: SuggestionFeedbackReason): SuggestionFeedback { return { events: current.events.map((event) => event.suggestionId === suggestionId ? { ...event, reason } : event) }; }
export function signalWeights(feedback: SuggestionFeedback): Record<SuggestionSignal, number> { const weights: Record<SuggestionSignal, number> = { "shared-tags": 0, "shared-neighbors": 0, "shared-source": 0, "same-kind": 0 }; feedback.events.forEach((event) => event.signals.forEach((signal) => { weights[signal] += event.outcome === "accepted" ? 0.75 : -0.5; })); return Object.fromEntries(Object.entries(weights).map(([signal, value]) => [signal, Math.max(-2, Math.min(3, value))])) as Record<SuggestionSignal, number>; }
export function feedbackDelta(feedback: SuggestionFeedback | undefined, signals: SuggestionSignal[]) { if (!feedback) return 0; const weights = signalWeights(feedback); return signals.reduce((total, signal) => total + weights[signal], 0); }
export function rankingSensitivity(feedback: SuggestionFeedback, signals: SuggestionSignal[], outcome: SuggestionOutcome) { const currentDelta = feedbackDelta(feedback, signals); const projected = appendSuggestionFeedback(feedback, { suggestionId: "__preview__", outcome, signals }, 0); const projectedDelta = feedbackDelta(projected, signals); return { currentDelta, projectedDelta, change: projectedDelta - currentDelta, outcome }; }
export function feedbackTimeline(feedback: SuggestionFeedback, limit = 5) { return feedback.events.slice(0, limit); }
export function isSuggestionDismissed(feedback: SuggestionFeedback, suggestionId: string) { return feedback.events.some((event) => event.suggestionId === suggestionId && event.outcome === "dismissed"); }
export function feedbackSummary(feedback: SuggestionFeedback) { const accepted = feedback.events.filter((event) => event.outcome === "accepted").length; const dismissed = feedback.events.filter((event) => event.outcome === "dismissed").length; const weights = signalWeights(feedback); return { accepted, dismissed, weights, adjustedSignals: (Object.values(weights) as number[]).filter((value) => value !== 0).length }; }
export function signalRecommendations(feedback: SuggestionFeedback) { const weights = signalWeights(feedback); return (Object.entries(weights) as [SuggestionSignal, number][]).filter(([, weight]) => Math.abs(weight) >= 1).map(([signal, weight]) => ({ signal, weight, tone: weight > 0 ? "reinforce" as const : "reduce" as const, message: weight > 0 ? `You consistently confirm ${signal.replace("shared-", "shared ").replace("same-kind", "matching kind")} signals. Keep this local signal influential.` : `You frequently dismiss ${signal.replace("shared-", "shared ").replace("same-kind", "matching kind")} signals. Treat this signal more cautiously.` })); }
export function createFeedbackProfileBundle(feedback: SuggestionFeedback, exportedAt = new Date().toISOString()): FeedbackProfileBundle { return { schemaVersion: 1, exportedAt, feedback }; }
export function serializeFeedbackProfile(feedback: SuggestionFeedback, exportedAt?: string) { return JSON.stringify(createFeedbackProfileBundle(feedback, exportedAt), null, 2); }
export function parseFeedbackProfile(raw: string): FeedbackProfileBundle { let parsed: unknown; try { parsed = JSON.parse(raw); } catch { throw new Error("The selected feedback profile is not valid JSON."); } if (!parsed || typeof parsed !== "object") throw new Error("The selected feedback profile is invalid."); const bundle = parsed as Partial<FeedbackProfileBundle>; if (bundle.schemaVersion !== 1 || typeof bundle.exportedAt !== "string" || !isSuggestionFeedback(bundle.feedback)) throw new Error("This file is not a compatible feedback profile."); return { schemaVersion: 1, exportedAt: bundle.exportedAt, feedback: bundle.feedback }; }
export function previewFeedbackImport(current: SuggestionFeedback, incoming: SuggestionFeedback): FeedbackImportPreview { const currentById = new Map(current.events.map((event) => [event.suggestionId, event])); let newEvents = 0; let newerReplacements = 0; let unchanged = 0; incoming.events.forEach((event) => { const existing = currentById.get(event.suggestionId); if (!existing) newEvents += 1; else if (event.createdAt > existing.createdAt) newerReplacements += 1; else unchanged += 1; }); return { incomingEvents: incoming.events.length, newEvents, newerReplacements, unchanged }; }
export function mergeSuggestionFeedback(current: SuggestionFeedback, incoming: SuggestionFeedback): SuggestionFeedback { const all = [...current.events, ...incoming.events].sort((left, right) => right.createdAt - left.createdAt); const seen = new Set<string>(); return { events: all.filter((event) => { if (seen.has(event.suggestionId)) return false; seen.add(event.suggestionId); return true; }).slice(0, 100) }; }
type SuggestionFeedbackValue = { feedback: SuggestionFeedback; isReady: boolean; recordFeedback: (event: Omit<SuggestionFeedbackEvent, "createdAt">) => void; updateReason: (suggestionId: string, reason: SuggestionFeedbackReason) => void; mergeFeedback: (incoming: SuggestionFeedback) => void; replaceFeedback: (incoming: SuggestionFeedback) => void; resetFeedback: () => void };
const SuggestionFeedbackContext = createContext<SuggestionFeedbackValue | null>(null);
export function SuggestionFeedbackProvider({ children }: PropsWithChildren) { const [feedback, setFeedback] = useState<SuggestionFeedback>(emptySuggestionFeedback); const [isReady, setIsReady] = useState(false); useEffect(() => { AsyncStorage.getItem(SUGGESTION_FEEDBACK_KEY).then((stored) => { if (!stored) return; try { const parsed: unknown = JSON.parse(stored); if (isSuggestionFeedback(parsed)) setFeedback(parsed); } catch { setFeedback(emptySuggestionFeedback()); } }).catch(() => undefined).finally(() => setIsReady(true)); }, []); useEffect(() => { if (isReady) void AsyncStorage.setItem(SUGGESTION_FEEDBACK_KEY, JSON.stringify(feedback)); }, [feedback, isReady]); const recordFeedback = useCallback((event: Omit<SuggestionFeedbackEvent, "createdAt">) => setFeedback((current) => appendSuggestionFeedback(current, event)), []); const updateReason = useCallback((suggestionId: string, reason: SuggestionFeedbackReason) => setFeedback((current) => updateFeedbackReason(current, suggestionId, reason)), []); const mergeFeedback = useCallback((incoming: SuggestionFeedback) => setFeedback((current) => mergeSuggestionFeedback(current, incoming)), []); const replaceFeedback = useCallback((incoming: SuggestionFeedback) => setFeedback({ events: incoming.events.slice(0, 100) }), []); const resetFeedback = useCallback(() => setFeedback(emptySuggestionFeedback()), []); const value = useMemo(() => ({ feedback, isReady, recordFeedback, updateReason, mergeFeedback, replaceFeedback, resetFeedback }), [feedback, isReady, recordFeedback, updateReason, mergeFeedback, replaceFeedback, resetFeedback]); return <SuggestionFeedbackContext.Provider value={value}>{children}</SuggestionFeedbackContext.Provider>; }
export function useSuggestionFeedback() { const context = useContext(SuggestionFeedbackContext); if (!context) throw new Error("useSuggestionFeedback must be used within SuggestionFeedbackProvider"); return context; }
